### ISSUE TITLE
Change of file permissions on save

### ISSUE THREAD

**Issue by dubourg** [jupyter/jupyter-js-editor#24]
Am I the only one experiencing a change of file permissions when saving? I am running jupyter in Wakari (self-hosted Anaconda cloud). The server runs Ubuntu 14.04 on a file system that is using ACL's.

**Comment by blink1073** [comment]
Hi @dubourg, this repository is deprecated and is not used by the notebook.  Please file your issue here: https://github.com/jupyter/notebook/issues.
